publishing:
  - 'src/styles/**' # 스타일링 관련 변경 (CSS, Tailwind 등)
  - 'src/components/**' # UI 컴포넌트 변경
  - 'public/assets/**' # 이미지, 아이콘 등 디자인 관련 리소스

feature:
  - 'src/features/**' # 새 기능 추가 관련 코드
  - 'src/hooks/**' # 커스텀 훅 관련 변경

api:
  - 'src/api/**' # API 요청 관련 코드
  - 'src/services/**' # API 서비스 로직

bug:
  - '.github/ISSUE_TEMPLATE/bug_report.md' # 버그 리포트 이슈
  - 'src/**/*.ts' # TS 코드 수정 감지

refactor:
  - 'src/utils/**' # 유틸 함수 변경
  - 'src/store/**' # Zustand, Redux 등 상태 관리 관련 변경

mvp:
  - '.github/ISSUE_TEMPLATE/mvp-task.yml' # MVP 기능 작업 이슈
