name: "[MVP] 기능 작업"
description: 모동구 프로젝트의 기능 개발 이슈를 작성합니다.
title: "[MVP] "
labels: ["mvp"]
body:
  - type: textarea
    id: description
    attributes:
      label: ✅ 기능 설명
      description: 어떤 기능인지 간단히 설명해주세요.
      placeholder: 예) 게시물 목록을 조회하고 리스트로 출력하는 기능
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: 📋 작업 목록
      description: 체크리스트 형식으로 작업 내용을 작성해주세요.
      placeholder: |
        - [ ] UI 구성
        - [ ] API 연동
    validations:
      required: false

  - type: input
    id: parent
    attributes:
      label: 🔗 관련 이슈 (예: #1)
      description: 상위 이슈 번호를 입력해주세요.
      placeholder: "#1"
    validations:
      required: true 