name: Code Quality Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: frontend/yarn.lock

      - name: Show environment info
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Node version: $(node -v)"
          echo "Yarn version: $(yarn -v)"

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          yarn install --frozen-lockfile
          echo "Dependencies installed successfully"
          echo "node_modules contents:"
          ls -la node_modules/.bin/

      - name: Type check
        run: |
          echo "Running type check..."
          yarn type-check

      - name: Lint check
        run: |
          echo "Running lint check..."
          yarn lint

      - name: Build check
        run: |
          echo "Running build check..."
          yarn build
